# Source spec for 04-units-of-work — regenerate with:
#   python3 scripts/gen_plan.py .ai/features/2026092202-question-review .ai/features/2026092202-question-review/plan_spec.py

UOWS = [
    dict(
        id="UOW-01", slug="triage-and-duplicates", title="Parsed questions are triaged and de-duplicated automatically",
        requirements=["US-01", "US-05"], risk="medium",
        demo=[
            "Upload samples/exams/de-mau-toan10.docx and de-kho.docx",
            "Open /org/review → each document shows Tự duyệt / Cần xem / Trùng counts and a progress bar",
            "Upload de-mau-toan10.pdf (same questions) → its questions are marked Trùng and linked to the docx ones",
            "As org_admin assign de-kho to a teacher → it appears under 'Của tôi' for that teacher",
        ],
        in_scope=["Migration (statuses, review_events, trgm)", "question_quality module", "Triage hook (search_text, dedupe, status, spot checks)",
                  "Review documents API + assignment", "Review list UI"],
    ),
    dict(
        id="UOW-02", slug="keyboard-review-queue", title="Teachers clear the review queue with single keys",
        requirements=["US-02", "US-03", "US-04"], depends_on=["UOW-01"], risk="high",
        demo=[
            "Open de-kho in /org/review → queue shows 'thiếu đáp án' group first, counter 1/5",
            "Press 2 → answer B saved; Enter → approved and next question shown",
            "Press E → edit the stem in Markdown with KaTeX preview → Ctrl+Enter saves",
            "Press X on a bad question → rejected; K goes back",
            "Open the PDF document's queue → source page image shown beside the question",
            "'Dán đáp án' with '1B 2B 3B 4B 5B' → summary 'Đã áp dụng 5'",
            "'Duyệt tất cả câu tin cậy cao' → auto-approved become approved",
        ],
        in_scope=["Queue + actions + edit API with events and spot-check loop", "Answer-key paste, approve-confident, PDF page images",
                  "Queue page with keyboard map", "Inline editor + bulk dialogs + review-flow test"],
    ),
    dict(
        id="UOW-03", slug="knn-learning", title="Approved questions teach topic suggestions",
        requirements=["US-04"], depends_on=["UOW-01"],
        demo=[
            "Approve Câu 2 of de-kho with topic 'Lũy thừa với số mũ thực'",
            "Upload a new file with a near-identical question → its suggested topic is 'Lũy thừa với số mũ thực' (source knn)",
        ],
        in_scope=["kNN suggestion via trigram similarity to approved questions"],
    ),
    dict(
        id="UOW-04", slug="question-bank", title="Teachers search, edit and create questions in the bank",
        requirements=["US-06", "US-03"], depends_on=["UOW-01"],
        demo=[
            "Open /org/bank, search 'parabol', filter Lớp 10 and topic 'Đại số' → vertex questions listed",
            "Open one, edit solution, add a tag, change difficulty → saved and rendered",
            "Click 'Thêm câu hỏi', paste an image into the stem, save → appears as approved manual",
            "Select 3 questions → set difficulty 'Vận dụng' in bulk",
            "Delete a question; filter 'Đã loại' → restore a rejected one",
        ],
        in_scope=["Search/filter/create/delete/bulk API", "Bank list with filters", "Question editor with image upload", "Bulk actions"],
    ),
]

API = "apps/api"
WEB = "apps/web"

TICKETS = [
    # ---------------- UOW-01
    dict(id="T-01-01", uow="UOW-01", title="Migration: review statuses, duplicate_of, search_text, review_events, pg_trgm/unaccent",
         layer="data", estimate="3h", verifies=["AC-01", "AC-03", "AC-13", "AC-14"],
         tests=[f"{API}/tests/test_review_schema.py"],
         touches=[f"{API}/migrations/versions/0007_review.py", f"{API}/app/models/question.py", f"{API}/app/models/review.py",
                  f"{API}/app/models/document.py", f"{API}/app/models/__init__.py"],
         assumptions=["A-01"],
         context="Existing draft questions are migrated through triage in the migration's data step.",
         done_when=["Extensions + GIN index created", "review_events append-only model", "Existing drafts re-triaged"]),
    dict(id="T-01-02", uow="UOW-01", title="question_quality module shared by splitter and edits",
         layer="domain", estimate="3h", depends_on=["T-01-01"], verifies=["AC-01", "AC-07"],
         tests=[f"{API}/tests/test_question_quality.py", f"{API}/tests/test_splitter.py"],
         touches=[f"{API}/app/services/question_quality.py", f"{API}/app/ingestion/splitter.py"],
         assumptions=["A-02"],
         context="ADR-02. validate(dict) -> (issues, confidence); triage_status(q, threshold).",
         done_when=["Splitter tests unchanged and green", "Blocking-issue list in one place"]),
    dict(id="T-01-03", uow="UOW-01", title="Triage hook: search_text, near-duplicates, status, spot-check sampling",
         layer="worker", estimate="4h", depends_on=["T-01-02"], verifies=["AC-01", "AC-03", "AC-11"],
         tests=[f"{API}/tests/test_triage.py"],
         touches=[f"{API}/app/services/triage.py", f"{API}/app/ingestion/pipeline.py", f"{API}/app/ingestion/jobs.py", f"{API}/app/services/search_text.py"],
         assumptions=["A-02", "A-03", "A-07"],
         context="Runs after persist; re-parse re-triages the new drafts only.",
         done_when=["Golden docx: ≤ 15% needs_review", "PDF copy of the docx marked duplicate", "Spot checks sampled"]),
    dict(id="T-01-04", uow="UOW-01", title="Review documents API (counts, progress, assignment)",
         layer="api", estimate="3h", depends_on=["T-01-03"], verifies=["AC-02", "AC-14", "AC-20"],
         tests=[f"{API}/tests/test_review_api.py"],
         touches=[f"{API}/app/routers/review.py", f"{API}/app/schemas/review.py", f"{API}/app/services/review.py", f"{API}/app/routers/__init__.py"],
         assumptions=["A-09"],
         done_when=["Counts by status per document", "Assignment org_admin only", "Isolation"],
         context="Counts grouped in one query."),
    dict(id="T-01-05", uow="UOW-01", title="Review list UI with progress and assignment",
         layer="web", estimate="3h", depends_on=["T-01-04"], verifies=["AC-02", "AC-14"],
         tests=[f"{WEB}/src/__tests__/review-list.test.tsx"],
         touches=[f"{WEB}/src/app/(app)/org/review/page.tsx", f"{WEB}/src/components/review/ReviewList.tsx", f"{WEB}/src/lib/types.ts", f"{WEB}/src/lib/nav.ts"],
         context="Filter 'Của tôi'; progress = (approved+auto+rejected+duplicate)/total.",
         done_when=["Counts and progress render", "Assign dropdown for org_admin"]),
    # ---------------- UOW-02
    dict(id="T-02-01", uow="UOW-02", title="Queue, actions, question edit API; review events; spot-check threshold loop",
         layer="api", estimate="4h", depends_on=["T-01-04"], verifies=["AC-04", "AC-05", "AC-07", "AC-11", "AC-13"],
         tests=[f"{API}/tests/test_review_queue.py"],
         touches=[f"{API}/app/services/review.py", f"{API}/app/routers/review.py", f"{API}/app/routers/questions.py", f"{API}/app/schemas/questions.py"],
         assumptions=["A-05", "A-07"],
         context="Approve refuses blocking issues (409). Edit recomputes quality.",
         done_when=["Queue ordering by issue group", "Events written for each action", "Threshold raised after 2/20 spot failures"]),
    dict(id="T-02-02", uow="UOW-02", title="Answer-key paste, approve-confident, rendered PDF pages",
         layer="api", estimate="3h", depends_on=["T-02-01"], verifies=["AC-04", "AC-08", "AC-09"],
         tests=[f"{API}/tests/test_review_bulk.py"],
         touches=[f"{API}/app/services/review.py", f"{API}/app/routers/review.py", f"{API}/app/routers/documents.py", f"{API}/app/services/answer_key.py"],
         assumptions=["A-04", "A-06"],
         context="Pages rendered with pypdfium2 and cached in MinIO.",
         done_when=["All paste formats parsed", "Page PNG served with cache headers"]),
    dict(id="T-02-03", uow="UOW-02", title="Keyboard review queue page",
         layer="web", estimate="4h", depends_on=["T-02-01", "T-01-05"], verifies=["AC-04", "AC-05", "AC-06"],
         tests=[f"{WEB}/src/components/review/ReviewQueue.test.tsx"],
         touches=[f"{WEB}/src/app/(app)/org/review/[id]/page.tsx", f"{WEB}/src/components/review/ReviewQueue.tsx", f"{WEB}/src/components/review/useHotkeys.ts"],
         assumptions=["A-05"],
         context="ADR-04. Optimistic updates with rollback.",
         done_when=["Every key mapped and tested", "Legend visible", "Source page shown for PDFs"]),
    dict(id="T-02-04", uow="UOW-02", title="Inline question editor, answer-key and approve-all dialogs, review-flow test",
         layer="web", estimate="4h", depends_on=["T-02-03", "T-02-02"], verifies=["AC-07", "AC-08", "AC-09"],
         tests=[f"{WEB}/src/components/review/QuestionEditor.test.tsx", f"{API}/tests/test_review_flow.py"],
         touches=[f"{WEB}/src/components/review/QuestionEditor.tsx", f"{WEB}/src/components/review/AnswerKeyDialog.tsx",
                  f"{WEB}/src/components/review/ReviewQueue.tsx", f"{API}/tests/test_review_flow.py"],
         context="Review-flow test replays golden docs: flagged ratio and actions per flagged question.",
         done_when=["Ctrl+Enter saves", "Flow test asserts ≤ 15% flagged and ≤ 2 actions each"]),
    # ---------------- UOW-03
    dict(id="T-03-01", uow="UOW-03", title="kNN topic suggestion from approved questions",
         layer="worker", estimate="3h", depends_on=["T-01-03"], verifies=["AC-12"],
         tests=[f"{API}/tests/test_knn.py"],
         touches=[f"{API}/app/ingestion/topic_suggest.py", f"{API}/app/services/triage.py"],
         assumptions=["A-08"],
         context="Weak keyword (< 0.6) or none → nearest approved question ≥ 0.35 similarity.",
         done_when=["knn source recorded", "Keyword kept when strong"]),
    # ---------------- UOW-04
    dict(id="T-04-01", uow="UOW-04", title="Bank API: search/filter (text, topic subtree, tags…), create, delete, bulk",
         layer="api", estimate="4h", depends_on=["T-01-03", "T-02-01"], verifies=["AC-10", "AC-15", "AC-16", "AC-18", "AC-19", "AC-20"],
         tests=[f"{API}/tests/test_bank_api.py"],
         touches=[f"{API}/app/services/bank.py", f"{API}/app/routers/questions.py", f"{API}/app/schemas/questions.py"],
         assumptions=["A-10", "A-11"],
         context="Topic filter uses ltree `<@`; text uses unaccent + trigram.",
         done_when=["All filters combine", "10k-question search < 300 ms", "Students 403"]),
    dict(id="T-04-02", uow="UOW-04", title="Bank list UI with filters and topic picker",
         layer="web", estimate="4h", depends_on=["T-04-01", "T-01-05"], verifies=["AC-15", "AC-16"],
         tests=[f"{WEB}/src/__tests__/bank.test.tsx"],
         touches=[f"{WEB}/src/app/(app)/org/bank/page.tsx", f"{WEB}/src/components/bank/BankFilters.tsx", f"{WEB}/src/components/bank/TopicPicker.tsx",
                  f"{WEB}/src/components/bank/QuestionRow.tsx", f"{WEB}/src/lib/nav.ts"],
         context="Filters in URL query so links are shareable.",
         done_when=["Filters + pagination", "Topic picker searchable"]),
    dict(id="T-04-03", uow="UOW-04", title="Question page: edit with image upload, create new",
         layer="web", estimate="4h", depends_on=["T-04-02", "T-02-04"], verifies=["AC-17", "AC-18"],
         tests=[f"{WEB}/src/__tests__/question-edit.test.tsx"],
         touches=[f"{WEB}/src/app/(app)/org/bank/[id]/page.tsx", f"{WEB}/src/app/(app)/org/bank/new/page.tsx", f"{WEB}/src/components/review/QuestionEditor.tsx"],
         context="Paste/drop an image → /api/assets → inserts ![](asset:id) at the cursor.",
         done_when=["Image upload inserts ref", "Create lands on the new question"]),
    dict(id="T-04-04", uow="UOW-04", title="Bulk actions and delete/restore in the bank",
         layer="web", estimate="3h", depends_on=["T-04-02"], verifies=["AC-10", "AC-19"],
         tests=[f"{WEB}/src/__tests__/bank-bulk.test.tsx"],
         touches=[f"{WEB}/src/components/bank/BulkBar.tsx", f"{WEB}/src/app/(app)/org/bank/page.tsx"],
         context="Selection checkboxes; bar appears when ≥ 1 selected.",
         done_when=["Bulk topic/difficulty/tags", "Delete + restore"]),
]
