# Source spec for 04-units-of-work — regenerate with:
#   python3 scripts/gen_plan.py .ai/features/2026092203-exam-practice .ai/features/2026092203-exam-practice/plan_spec.py

UOWS = [
    dict(
        id="UOW-01", slug="exam-builder", title="Teachers build exams from blueprints or by hand",
        requirements=["US-01", "US-06"], risk="medium",
        demo=[
            "Staff pages use the new grouped sidebar (also on a 375 px phone as a drawer)",
            "Open /org/exams → 'Tạo đề' → title 'Kiểm tra 15 phút', rows (Đại số · Trắc nghiệm · 6), (Hình học · Trắc nghiệm · 4) → 10 questions",
            "Add a row that cannot be filled → 'thiếu N câu' warning",
            "Swap one question, remove one, add one from bank search, drag to reorder; change MCQ points to 0.5 → total updates",
            "'Xem trước' shows the exam as students see it; toggle answers",
            "Try deleting a used question in the bank → 'đang được dùng trong đề'",
        ],
        in_scope=["Schema for exams, assignments, attempts, facts", "Scoring module", "Exams API + blueprint builder", "Sidebar nav", "Exams UI"],
    ),
    dict(
        id="UOW-02", slug="assign-and-take", title="Students take assigned exams with a timer and autosave",
        requirements=["US-02", "US-03", "US-04", "US-06"], depends_on=["UOW-01"], risk="high",
        demo=[
            "Assign 'Kiểm tra 15 phút' to 10A1: now → +1 day, 15 minutes, shuffle on, results after submit",
            "Log in as a 10A1 student → /home shows it under 'Đang mở'",
            "Start → countdown, navigator, answers hidden; answer 5 questions, reload → answers and time restored",
            "Switch tab and back → counted",
            "Submit → score out of 10 appears immediately",
            "Start an assignment whose window closed → refused",
        ],
        in_scope=["Assignments API + student home API", "Attempts: start, answers, submit, expiry, grading, facts", "Assign dialog + student home", "Exam page"],
    ),
    dict(
        id="UOW-03", slug="results-and-grading", title="Students see feedback; teachers grade essays",
        requirements=["US-04"], depends_on=["UOW-02"],
        demo=[
            "Student opens the result: each question shows their answer, the key and the solution; breakdown by section and topic",
            "An 'after close' assignment shows only the total before closing",
            "Teacher opens an attempt with an essay, gives 1.5/2 with a comment → student total updates and shows the comment",
        ],
        in_scope=["Result API with policies", "Essay grading API", "Result page", "Teacher attempt view with grading"],
    ),
    dict(
        id="UOW-04", slug="reports", title="Teachers and students see where marks were lost",
        requirements=["US-05", "US-06"], depends_on=["UOW-02"],
        demo=[
            "Assignment report: submitted/not submitted, average, distribution, per-question % correct and most-chosen wrong option",
            "'Theo chuyên đề': tree with % correct at every level (Đại số 70% › Hàm số bậc hai 60% › …)",
            "Group by tag / type / difficulty; filter by class",
            "Class heatmap students × strands",
            "Student 'Tiến độ của tôi': weakest topics first",
        ],
        in_scope=["Stats API (topics, groups, heatmap, assignment report)", "Report pages", "My stats page"],
    ),
]

API = "apps/api"
WEB = "apps/web"

TICKETS = [
    # ---------------- UOW-01
    dict(id="T-01-01", uow="UOW-01", title="Schema: exams, exam_questions, assignments, targets, attempts, answers, answer_facts",
         layer="data", estimate="3h", verifies=["AC-01", "AC-05", "AC-07", "AC-17"],
         tests=[f"{API}/tests/test_exam_schema.py"],
         touches=[f"{API}/migrations/versions/0009_exams.py", f"{API}/app/models/exam.py", f"{API}/app/models/__init__.py"],
         assumptions=["A-01", "A-05", "A-09"],
         context="Domain model table in 03-logical-design.md.",
         done_when=["Constraints + indexes (GiST on answer_facts.topic_path)", "Up/down clean"]),
    dict(id="T-01-02", uow="UOW-01", title="Scoring module (MCQ, true/false partial credit, short answer normalisation, scaling)",
         layer="domain", estimate="3h", verifies=["AC-03", "AC-11"],
         tests=[f"{API}/tests/test_scoring.py"],
         touches=[f"{API}/app/services/scoring.py"],
         assumptions=["A-02", "A-03"],
         context="ADR-04. Pure functions.",
         done_when=["THPT 2025 partial table", "2,5 == 2.5 == 5/2", "Scale to 10"]),
    dict(id="T-01-03", uow="UOW-01", title="Exams API: CRUD, blueprint builder, add/remove/reorder/swap/points, in-use guard",
         layer="api", estimate="4h", depends_on=["T-01-01", "T-01-02"], verifies=["AC-01", "AC-02", "AC-03", "AC-15"],
         tests=[f"{API}/tests/test_exams_api.py"],
         touches=[f"{API}/app/services/exams.py", f"{API}/app/routers/exams.py", f"{API}/app/schemas/exams.py", f"{API}/app/routers/__init__.py", f"{API}/app/services/bank.py"],
         assumptions=["A-01", "A-04", "A-11"],
         context="Blueprint uses bank.search filters; seeded random.",
         done_when=["Shortfalls reported", "Distinct questions", "Bank delete refused for used questions"]),
    dict(id="T-01-04", uow="UOW-01", title="Grouped sidebar navigation (drawer on phones)",
         layer="web", estimate="3h", verifies=["AC-22"],
         tests=[f"{WEB}/src/__tests__/nav.test.tsx"],
         touches=[f"{WEB}/src/lib/nav.ts", f"{WEB}/src/app/(app)/AppShell.tsx"],
         context="ADR-05.",
         done_when=["Groups by role", "Mobile drawer"]),
    dict(id="T-01-05", uow="UOW-01", title="Exams UI: list, builder (blueprint rows, bank add, reorder, swap, points), preview",
         layer="web", estimate="4h", depends_on=["T-01-03", "T-01-04"], verifies=["AC-01", "AC-02", "AC-03", "AC-04"],
         tests=[f"{WEB}/src/__tests__/exam-builder.test.tsx"],
         touches=[f"{WEB}/src/app/(app)/org/exams/page.tsx", f"{WEB}/src/app/(app)/org/exams/[id]/page.tsx",
                  f"{WEB}/src/components/exams/BlueprintEditor.tsx", f"{WEB}/src/components/exams/ExamQuestions.tsx", f"{WEB}/src/lib/types.ts"],
         context="Reorder with up/down buttons (keyboard-accessible) instead of drag.",
         done_when=["Rows + shortfall warnings", "Total points", "Preview toggle"]),
    # ---------------- UOW-02
    dict(id="T-02-01", uow="UOW-02", title="Assignments API, student home API, start attempt",
         layer="api", estimate="4h", depends_on=["T-01-03"], verifies=["AC-05", "AC-06", "AC-20"],
         tests=[f"{API}/tests/test_assignments_api.py"],
         touches=[f"{API}/app/services/assignments.py", f"{API}/app/routers/assignments.py", f"{API}/app/schemas/assignments.py", f"{API}/app/routers/__init__.py"],
         assumptions=["A-05", "A-06", "A-10"],
         context="Start resumes an in-progress attempt; computes deadline; stores shuffled orders.",
         done_when=["Window + attempts enforced", "Targets via classes and users"]),
    dict(id="T-02-02", uow="UOW-02", title="Attempts: view, autosave answers, submit, tab switches, expiry sweep, grading → answer_facts",
         layer="api", estimate="4h", depends_on=["T-02-01"], verifies=["AC-07", "AC-08", "AC-09", "AC-10", "AC-11", "AC-15"],
         tests=[f"{API}/tests/test_attempts_api.py"],
         touches=[f"{API}/app/services/attempts.py", f"{API}/app/routers/attempts.py", f"{API}/app/worker/main.py", f"{API}/app/ingestion/jobs.py"],
         assumptions=["A-06", "A-07", "A-11", "A-12"],
         context="ADR-02, ADR-03. Student view never leaks keys.",
         done_when=["Late answers 409", "Expired attempts finalised by access and sweep", "Facts written per answer"]),
    dict(id="T-02-03", uow="UOW-02", title="Assign dialog and student home",
         layer="web", estimate="3h", depends_on=["T-02-01", "T-01-05"], verifies=["AC-05", "AC-20"],
         tests=[f"{WEB}/src/__tests__/assign.test.tsx"],
         touches=[f"{WEB}/src/components/exams/AssignDialog.tsx", f"{WEB}/src/app/(app)/home/page.tsx", f"{WEB}/src/app/(app)/org/exams/[id]/page.tsx"],
         context="Home sections: Đang mở / Sắp tới / Đã làm.",
         done_when=["Assign with classes and window", "Home sections render"]),
    dict(id="T-02-04", uow="UOW-02", title="Exam taking page: timer, navigator, autosave queue, submit, tab switch, mobile",
         layer="web", estimate="4h", depends_on=["T-02-02", "T-02-03"], verifies=["AC-07", "AC-08", "AC-09", "AC-10"],
         tests=[f"{WEB}/src/components/exams/ExamRunner.test.tsx"],
         touches=[f"{WEB}/src/app/(app)/exam/[id]/page.tsx", f"{WEB}/src/components/exams/ExamRunner.tsx", f"{WEB}/src/components/exams/AnswerInput.tsx"],
         context="Server time offset from response headers; debounced PUT per question.",
         done_when=["Countdown from server deadline", "Unsaved banner + retry", "Works at 375 px"]),
    # ---------------- UOW-03
    dict(id="T-03-01", uow="UOW-03", title="Result API with policies; essay grading",
         layer="api", estimate="3h", depends_on=["T-02-02"], verifies=["AC-12", "AC-13", "AC-14"],
         tests=[f"{API}/tests/test_results_api.py"],
         touches=[f"{API}/app/services/attempts.py", f"{API}/app/routers/attempts.py"],
         assumptions=["A-08"],
         context="Breakdown by section and topic from answer_facts.",
         done_when=["Policies enforced", "Essay grade updates facts and totals"]),
    dict(id="T-03-02", uow="UOW-03", title="Result page and teacher attempt/grading view",
         layer="web", estimate="4h", depends_on=["T-03-01", "T-02-04"], verifies=["AC-12", "AC-13", "AC-14"],
         tests=[f"{WEB}/src/__tests__/result.test.tsx"],
         touches=[f"{WEB}/src/app/(app)/results/[id]/page.tsx", f"{WEB}/src/components/exams/ResultView.tsx", f"{WEB}/src/components/exams/EssayGrader.tsx"],
         context="QuestionView result mode with the student's choice.",
         done_when=["Per-question feedback", "Hidden policy message", "Essay grading form"]),
    # ---------------- UOW-04
    dict(id="T-04-01", uow="UOW-04", title="Stats API: topic tree roll-up, groups, heatmap, assignment report",
         layer="api", estimate="4h", depends_on=["T-02-02"], verifies=["AC-16", "AC-17", "AC-18", "AC-19", "AC-21"],
         tests=[f"{API}/tests/test_stats_api.py"],
         touches=[f"{API}/app/services/stats.py", f"{API}/app/routers/stats.py", f"{API}/app/routers/assignments.py", f"{API}/app/routers/__init__.py"],
         assumptions=["A-09", "A-10"],
         context="ltree roll-up: facts joined to topics where topic.path @> fact.topic_path.",
         done_when=["Roll-up correct on a fixture tree", "Students limited to own data", "< 500 ms on the perf fixture"]),
    dict(id="T-04-02", uow="UOW-04", title="Assignment report page",
         layer="web", estimate="3h", depends_on=["T-04-01", "T-02-03"], verifies=["AC-16"],
         tests=[f"{WEB}/src/__tests__/assignment-report.test.tsx"],
         touches=[f"{WEB}/src/app/(app)/org/assignments/[id]/page.tsx", f"{WEB}/src/components/reports/AssignmentReport.tsx"],
         context="Links to each attempt (teacher view).",
         done_when=["Distribution bars", "Per-question table"]),
    dict(id="T-04-03", uow="UOW-04", title="Reports page: topic tree stats, groups, heatmap",
         layer="web", estimate="4h", depends_on=["T-04-01", "T-01-04"], verifies=["AC-17", "AC-18", "AC-19"],
         tests=[f"{WEB}/src/components/reports/TopicStatsTree.test.tsx"],
         touches=[f"{WEB}/src/app/(app)/org/reports/page.tsx", f"{WEB}/src/components/reports/TopicStatsTree.tsx",
                  f"{WEB}/src/components/reports/GroupStats.tsx", f"{WEB}/src/components/reports/Heatmap.tsx"],
         context="Colour scale red→green by ratio; counts shown.",
         done_when=["Expandable tree with ratios", "Group tabs", "Heatmap"]),
    dict(id="T-04-04", uow="UOW-04", title="My stats page for students",
         layer="web", estimate="2h", depends_on=["T-04-03"], verifies=["AC-21"],
         tests=[f"{WEB}/src/__tests__/my-stats.test.tsx"],
         touches=[f"{WEB}/src/app/(app)/me/stats/page.tsx"],
         context="Reuses TopicStatsTree and GroupStats; weakest first.",
         done_when=["Weakest topics list", "Tree"]),
]
