import { dirname } from "path";
import { fileURLToPath } from "url";
import { FlatCompat } from "@eslint/eslintrc";

const __filename = fileURLToPath(import.meta.url);
const __dirname = dirname(__filename);

const compat = new FlatCompat({
  baseDirectory: __dirname,
});

const eslintConfig = [
  ...compat.extends("next/core-web-vitals", "next/typescript"),
  {
    // ui-shadcn-shell ADR-01: import each shadcn component from its own file, as in the shadcn docs.
    rules: {
      "no-restricted-imports": [
        "error",
        {
          paths: [{ name: "@/components/ui", message: 'Import from "@/components/ui/<component>" (shadcn) instead.' }],
          patterns: [{ group: ["@/components/ui/index"], message: "There is no components/ui barrel." }],
        },
      ],
    },
  },
  {
    // files generated by the shadcn CLI are kept verbatim
    files: ["src/components/ui/**"],
    rules: { "@typescript-eslint/no-empty-object-type": "off", "react-hooks/purity": "off" },
  },
  {
    ignores: [
      "node_modules/**",
      ".next/**",
      "out/**",
      "build/**",
      "next-env.d.ts",
    ],
  },
];

export default eslintConfig;
