"""The metadata (every shared/infrastructure/schema table and module mapping) matches what the migrations build
(architecture-refactor T-07-03): `alembic check` finds nothing to generate."""
import os
import warnings

from alembic import command
from alembic.config import Config

from tests.conftest import HERE, TEST_URL


def test_metadata_matches_the_migrations(_database):
    cfg = Config(os.path.join(HERE, "alembic.ini"))
    cfg.set_main_option("script_location", os.path.join(HERE, "migrations"))
    cfg.attributes["url"] = TEST_URL
    with warnings.catch_warnings():
        warnings.simplefilter("ignore")
        command.check(cfg)  # raises AutogenerateDiffsDetected on any drift
