# Source spec for 04-units-of-work — regenerate with:
#   python3 scripts/gen_plan.py .ai/features/2026092201-exam-ingestion .ai/features/2026092201-exam-ingestion/plan_spec.py

UOWS = [
    dict(
        id="UOW-01", slug="word-exam-to-questions", title="A Word exam becomes complete draft questions",
        requirements=["US-01", "US-02"], risk="high",
        demo=[
            "docker compose up -d --build (worker included)",
            "Log in as a trungtama teacher, open /org/documents",
            "Upload samples/exams/de-mau-toan10.docx with Toán · Lớp 10 · HK1 · Giữa kỳ",
            "Status goes Đang chờ → Đang xử lý → Đã tách (40 câu) within a minute",
            "Open the document: every question shows stem, 4 options, answer, solution; equations render; the figure in Câu 5's option C and in Câu 12's solution appear",
            "Upload the same file again → redirected to the existing document with 'File này đã được tải lên'",
            "Upload a .doc → field error",
            "Upload samples/exams/de-thpt2025-toan.docx → PHẦN I mcq, PHẦN II true/false with Đ/S, PHẦN III short answers",
        ],
        in_scope=["Worker + Postgres job queue", "Documents schema and API", "Pandoc docx extractor",
                  "Rule-based splitter (answers, answer keys, trailing solutions, parts, confidence)",
                  "Documents UI (upload, list, detail with QuestionView)", "Sample exam files + golden test"],
        not_in_scope=["PDF/scans (UOW-02)", "AI models and fallback (UOW-03)", "Topic suggestion (UOW-04)"],
        risks=[("Real exams deviate from the sample formats", "Splitter rules isolated and table-tested; golden set extended with real files at final review")],
        dod=["Worker image builds on arm64 with pandoc and tesseract", "40-question docx parsed < 60 s"],
    ),
    dict(
        id="UOW-02", slug="pdf-and-scans", title="Text PDFs and scanned exams are read",
        requirements=["US-03"], depends_on=["UOW-01"],
        demo=[
            "Upload samples/exams/de-mau-toan10.pdf → 40 questions, figure cropped into the right question",
            "Upload samples/exams/de-scan.png (and de-scan.pdf) → questions split, each flagged 'OCR' with confidence ≤ 0.8",
        ],
        in_scope=["pdfplumber extractor with two-column ordering and image crops", "OCR provider interface + Tesseract", "PDF/scan samples + golden tests"],
        risks=[("Two-column PDFs mis-ordered", "Column detection by word x-gap; tested on a two-column sample")],
    ),
    dict(
        id="UOW-03", slug="ai-model-choice", title="Admins register AI models; teachers choose them per upload",
        requirements=["US-04", "US-05"], depends_on=["UOW-01"],
        demo=[
            "As org_admin open /org/ai-models → 'Phát hiện model Ollama' lists pulled models; add one; 'Kiểm tra' → ok",
            "Add an OpenAI-compatible model with an API key → list shows 'Có khóa', key never shown",
            "As super_admin add a system model → org admin sees it as 'Hệ thống', cannot edit",
            "Open /org/settings/ingestion, set default mode 'Quy tắc + AI' and the model",
            "Upload samples/exams/de-kho.docx with 'Cấu hình xử lý' → rule+AI → low-confidence questions show parse_method AI and the model name",
            "Stop the model server, re-parse → questions keep rule results with issue 'AI không phản hồi'",
        ],
        in_scope=["ai_models registry + encryption + permissions", "Ollama/OpenAI-compatible/Anthropic adapters, discover, test",
                  "AI fallback with model chain, vision OCR engine, re-parse", "Org ingestion defaults", "AI models UI, upload config, re-parse UI"],
        risks=[("No local model on the dev machine", "Adapters tested against a stub HTTP server; smoke test with a small Ollama model")],
    ),
    dict(
        id="UOW-04", slug="topic-suggestions", title="Parsed questions carry metadata and a suggested topic",
        requirements=["US-06"], depends_on=["UOW-01"],
        demo=[
            "Open the parsed de-mau-toan10 document",
            "Each question shows Toán · Lớp 10 · HK1 · Giữa kỳ, source tag, and a suggested topic chip (e.g. 'Hàm số bậc hai và đồ thị' 0.8)",
            "With a tagging model configured, re-parse → suggestions marked AI",
        ],
        in_scope=["Keyword topic suggester", "LLM tagger among leaf topics", "Document page shows metadata + suggestions"],
    ),
]

API = "apps/api"
WEB = "apps/web"
ING = f"{API}/app/ingestion"

TICKETS = [
    # ---------------- UOW-01
    dict(id="T-01-01", uow="UOW-01", title="Image with pandoc/tesseract, worker + api-test services, verify.sh in container",
         layer="infra", type="chore", estimate="2h", verifies=["AC-01"],
         tests=[f"{API}/tests/test_health.py"],
         touches=[f"{API}/Dockerfile", "docker-compose.yml", "docker-compose.dev.yml", "scripts/verify.sh", ".env.example", f"{API}/pyproject.toml"],
         assumptions=["A-09"],
         context="ADR-06: API tests move into the api image so pandoc/tesseract match production.",
         notes=["Debian packages: pandoc, tesseract-ocr, tesseract-ocr-vie, fonts-dejavu-core", "worker service: same image, command `python -m app.worker.main`",
                "api-test: profile test, target test, bind-mount apps/api, TEST_DATABASE_URL on the compose network"],
         done_when=["`docker compose up` starts worker healthy", "verify.sh runs API tests inside the container", "`pandoc --version` and `tesseract --list-langs | grep vie` work in the image"]),
    dict(id="T-01-02", uow="UOW-01", title="Schema: jobs, source_documents, question provenance, question_topics/tags",
         layer="data", estimate="3h", depends_on=["T-01-01"], verifies=["AC-01", "AC-21"],
         tests=[f"{API}/tests/test_ingestion_schema.py"],
         touches=[f"{API}/migrations/versions/0005_ingestion.py", f"{API}/app/models/document.py", f"{API}/app/models/job.py",
                  f"{API}/app/models/question.py", f"{API}/app/models/asset.py", f"{API}/app/models/__init__.py"],
         assumptions=["A-08", "A-12"],
         context="Extends Question with provenance; adds link tables used by review and stats later.",
         done_when=["Migration up/down clean", "unique (org, file_hash) on documents", "question_topics PK and is_primary partial unique index"]),
    dict(id="T-01-03", uow="UOW-01", title="Postgres job queue and worker loop (retries, stale locks)",
         layer="worker", estimate="2h", depends_on=["T-01-02"], verifies=["AC-04"],
         tests=[f"{API}/tests/test_jobs.py"],
         touches=[f"{API}/app/worker/queue.py", f"{API}/app/worker/main.py"],
         assumptions=["A-09"],
         context="ADR-01. Handlers registered by kind; `ingest_document` added in T-01-06.",
         done_when=["Two workers never claim the same job", "Failure retried with backoff then marked failed", "Stale lock re-queued"]),
    dict(id="T-01-04", uow="UOW-01", title="Rule-based splitter over the line stream",
         layer="domain", estimate="4h", depends_on=["T-01-01"], verifies=["AC-05", "AC-07", "AC-08", "AC-09", "AC-10"],
         tests=[f"{API}/tests/test_splitter.py"],
         touches=[f"{ING}/__init__.py", f"{ING}/lines.py", f"{ING}/splitter.py"],
         assumptions=["A-01", "A-02", "A-03", "A-04"],
         context="ADR-02: pure function, table-tested with synthetic line streams.",
         notes=["Question header regex, part headers, options on one or many lines", "Answer sources: inline, key list/table, formatting", "Trailing solutions section re-uses numbering"],
         done_when=["All listed layouts covered by tests", "Confidence ≥ 0.85 for well-formed, < 0.85 with issues otherwise"]),
    dict(id="T-01-05", uow="UOW-01", title="Sample exam files (docx) generator",
         layer="test", type="test", estimate="2h", depends_on=["T-01-01"], verifies=["AC-05", "AC-06", "AC-09"],
         tests=[f"{API}/tests/test_samples.py"],
         touches=[f"{API}/scripts/make_samples.py", "samples/exams/"],
         context="Generates de-mau-toan10.docx (40 MCQ, OMML math, images, answer key, trailing solutions), de-thpt2025-toan.docx, de-kho.docx via Pandoc.",
         done_when=["Samples committed and reproducible"]),
    dict(id="T-01-06", uow="UOW-01", title="Docx extractor via Pandoc (math, images, underline marks)",
         layer="worker", estimate="3h", depends_on=["T-01-04", "T-01-05"], verifies=["AC-06", "AC-07"],
         tests=[f"{API}/tests/test_docx_extract.py"],
         touches=[f"{ING}/docx.py", f"{ING}/assets.py"],
         assumptions=["A-05"],
         context="Pandoc to markdown with extracted media → upload images as assets → Line stream.",
         notes=["EMF/WMF images skipped with a warning (not browser-safe)"],
         done_when=["Math lines contain $…$", "Images become asset refs at their position", "Underlined option label detected"]),
    dict(id="T-01-07", uow="UOW-01", title="Documents API + ingest pipeline (persist, metadata, source tag) + golden test",
         layer="api", estimate="4h", depends_on=["T-01-03", "T-01-06"], verifies=["AC-01", "AC-02", "AC-03", "AC-21"],
         tests=[f"{API}/tests/test_documents_api.py", f"{API}/tests/test_ingestion_golden.py"],
         touches=[f"{API}/app/routers/documents.py", f"{API}/app/schemas/documents.py", f"{API}/app/services/documents.py",
                  f"{ING}/pipeline.py", f"{API}/app/routers/__init__.py"],
         assumptions=["A-07", "A-08", "A-12", "A-14"],
         context="Upload validation, dedupe by hash, job enqueue, pipeline orchestration and persistence.",
         done_when=["Golden: ≥ 95% questions exact on de-mau-toan10.docx", "Parse time < 60 s asserted", "Re-parse keeps approved questions"]),
    dict(id="T-01-08", uow="UOW-01", title="Documents UI: upload, list with live status, detail with parsed questions",
         layer="web", estimate="3h", depends_on=["T-01-07"], verifies=["AC-01", "AC-02", "AC-03"],
         tests=[f"{WEB}/src/__tests__/documents.test.tsx"],
         touches=[f"{WEB}/src/app/(app)/org/documents/page.tsx", f"{WEB}/src/app/(app)/org/documents/[id]/page.tsx",
                  f"{WEB}/src/components/documents/UploadForm.tsx", f"{WEB}/src/components/documents/DocumentList.tsx",
                  f"{WEB}/src/components/documents/ParsedQuestion.tsx", f"{WEB}/src/lib/types.ts", f"{WEB}/src/lib/nav.ts"],
         context="Poll every 2 s while queued/processing. Parsed questions render with QuestionView in review mode + confidence/issues.",
         done_when=["Upload with metadata", "Duplicate notice", "Errors shown", "Detail renders questions"]),
    # ---------------- UOW-02
    dict(id="T-02-01", uow="UOW-02", title="Text PDF extractor (reading order, columns, image crops)",
         layer="worker", estimate="4h", depends_on=["T-01-07"], verifies=["AC-11"],
         tests=[f"{API}/tests/test_pdf_extract.py"],
         touches=[f"{ING}/pdf.py", f"{API}/scripts/make_samples.py", "samples/exams/"],
         context="ADR-04. Generate de-mau-toan10.pdf (and a two-column variant) in make_samples.",
         done_when=["Reading order correct on 1- and 2-column samples", "Figures cropped at their position"]),
    dict(id="T-02-02", uow="UOW-02", title="OCR provider interface + Tesseract; scanned PDF and image path",
         layer="worker", estimate="4h", depends_on=["T-02-01"], verifies=["AC-12"],
         tests=[f"{API}/tests/test_ocr.py"],
         touches=[f"{ING}/ocr.py", f"{ING}/pipeline.py", f"{API}/scripts/make_samples.py", "samples/exams/"],
         assumptions=["A-06"],
         context="ADR-05. Pages without text layer → render 300 dpi → OCR; OCR'd questions flagged.",
         done_when=["Scan sample splits into questions", "OCR flag + confidence cap"]),
    # ---------------- UOW-03
    dict(id="T-03-01", uow="UOW-03", title="ai_models registry: schema, encryption, CRUD API, permissions",
         layer="api", estimate="4h", depends_on=["T-01-02"], verifies=["AC-13", "AC-15"],
         tests=[f"{API}/tests/test_ai_models_api.py"],
         touches=[f"{API}/migrations/versions/0006_ai_models.py", f"{API}/app/models/ai_model.py", f"{API}/app/core/crypto.py",
                  f"{API}/app/services/ai_models.py", f"{API}/app/routers/ai_models.py", f"{API}/app/schemas/ai_models.py"],
         assumptions=["A-10", "A-11"],
         context="ADR-07. System models: organization_id NULL, super_admin only.",
         done_when=["Keys never returned", "Org isolation", "System models read-only for org admins"]),
    dict(id="T-03-02", uow="UOW-03", title="LLM adapters (Ollama, OpenAI-compatible, Anthropic), discover and test",
         layer="worker", estimate="4h", depends_on=["T-03-01"], verifies=["AC-14"],
         tests=[f"{API}/tests/test_llm.py"],
         touches=[f"{ING}/llm.py", f"{API}/app/routers/ai_models.py"],
         assumptions=["A-10"],
         context="ADR-03. JSON-mode chat with timeout; tested against an in-process stub server.",
         done_when=["Three adapters pass stub tests", "discover lists Ollama tags", "test endpoint reports latency/errors"]),
    dict(id="T-03-03", uow="UOW-03", title="AI fallback in pipeline, model chain, vision OCR engine, re-parse",
         layer="worker", estimate="4h", depends_on=["T-03-02", "T-02-02"], verifies=["AC-16", "AC-18", "AC-19", "AC-20"],
         tests=[f"{API}/tests/test_ai_fallback.py"],
         touches=[f"{ING}/pipeline.py", f"{ING}/ai_split.py", f"{ING}/ocr.py", f"{API}/app/routers/documents.py", f"{API}/app/services/documents.py"],
         assumptions=["A-14"],
         done_when=["Low-confidence blocks re-split by the model", "Chain fallback + issue on total failure", "Re-parse with new config"],
         context="Config resolved: upload > org default > system default."),
    dict(id="T-03-04", uow="UOW-03", title="Org ingestion defaults API",
         layer="api", estimate="2h", depends_on=["T-03-01"], verifies=["AC-17"],
         tests=[f"{API}/tests/test_ingestion_settings.py"],
         touches=[f"{API}/app/routers/org_settings.py", f"{API}/app/services/ingestion_settings.py"],
         context="Stored in organizations.settings.ingestion; validated against visible models.",
         done_when=["GET for staff, PUT for org_admin", "Invalid model ids refused"]),
    dict(id="T-03-05", uow="UOW-03", title="AI models UI (list, add, discover Ollama, test, edit, delete)",
         layer="web", estimate="4h", depends_on=["T-03-02", "T-01-08"], verifies=["AC-13", "AC-14", "AC-15"],
         tests=[f"{WEB}/src/__tests__/ai-models.test.tsx"],
         touches=[f"{WEB}/src/app/(app)/org/ai-models/page.tsx", f"{WEB}/src/components/ai/ModelForm.tsx", f"{WEB}/src/components/ai/ModelTable.tsx"],
         context="System models shown read-only with 'Hệ thống' badge; super_admin sees the same page for system models.",
         done_when=["All actions reachable", "Free/paid + has-key badges"]),
    dict(id="T-03-06", uow="UOW-03", title="Upload 'Cấu hình xử lý', org defaults page, re-parse action",
         layer="web", estimate="4h", depends_on=["T-03-04", "T-03-05", "T-03-03"], verifies=["AC-16", "AC-17", "AC-20"],
         tests=[f"{WEB}/src/__tests__/processing-config.test.tsx"],
         touches=[f"{WEB}/src/components/documents/ProcessingConfig.tsx", f"{WEB}/src/components/documents/UploadForm.tsx",
                  f"{WEB}/src/app/(app)/org/settings/ingestion/page.tsx", f"{WEB}/src/app/(app)/org/documents/[id]/page.tsx", f"{WEB}/src/lib/nav.ts"],
         context="Collapsed by default; seeded from org defaults.",
         done_when=["Config sent with upload and re-parse", "Defaults page saves"]),
    # ---------------- UOW-04
    dict(id="T-04-01", uow="UOW-04", title="Topic suggester: keyword rules + LLM tagger; persist question_topics",
         layer="domain", estimate="4h", depends_on=["T-01-07", "T-03-03"], verifies=["AC-22"],
         tests=[f"{API}/tests/test_topic_suggest.py"],
         touches=[f"{ING}/topic_suggest.py", f"{ING}/pipeline.py"],
         assumptions=["A-13"],
         context="Keyword index from leaf topic names + synonyms; LLM picks among leaf ids when a tag model is configured.",
         done_when=["Sample questions get sensible primary topics", "LLM choice validated against leaf ids"]),
    dict(id="T-04-02", uow="UOW-04", title="Document page shows metadata, source tag and suggested topics",
         layer="web", estimate="2h", depends_on=["T-04-01", "T-01-08"], verifies=["AC-21", "AC-22"],
         tests=[f"{WEB}/src/__tests__/parsed-question.test.tsx"],
         touches=[f"{WEB}/src/components/documents/ParsedQuestion.tsx"],
         context="Chips for subject/grade/semester/kind, source tag, topic suggestion with score and AI mark.",
         done_when=["Chips render", "Score shown"]),
]
