from datetime import date, datetime
from typing import Protocol
import uuid

from app.modules.academic.domain.entities import Grade, SchoolClass, SchoolLevel, SchoolYear


class SchoolYearRepository(Protocol):
    def get(self, org_id: uuid.UUID, year_id: uuid.UUID) -> SchoolYear | None: ...

    def by_code(self, org_id: uuid.UUID, code: str) -> SchoolYear | None: ...

    def active(self, org_id: uuid.UUID) -> SchoolYear | None: ...

    def covering(self, org_id: uuid.UUID, day: date) -> SchoolYear | None:
        """The latest-starting year whose dates contain `day`."""
        ...

    def class_count(self, year_id: uuid.UUID) -> int: ...

    def add(self, year: SchoolYear) -> None: ...

    def remove(self, year: SchoolYear) -> None: ...

    def flush(self) -> None: ...


class ClassRepository(Protocol):
    def get(self, org_id: uuid.UUID, class_id: uuid.UUID) -> SchoolClass | None: ...

    def find(self, org_id: uuid.UUID, name: str, school_year: str, exclude_id: uuid.UUID | None = None) -> SchoolClass | None:
        """The class of that name in that year (codes, as the unique key)."""
        ...

    def in_year(self, year_id: uuid.UUID, name: str) -> SchoolClass | None: ...

    def names_in_year(self, year_id: uuid.UUID) -> set[str]: ...

    def of_year(self, year_id: uuid.UUID) -> list[SchoolClass]:
        """By grade, then name."""
        ...

    def with_grade(self, grade_id: uuid.UUID) -> list[SchoolClass]: ...

    def add(self, klass: SchoolClass) -> None: ...

    def remove(self, klass: SchoolClass) -> None: ...

    def add_members(self, class_id: uuid.UUID, user_ids: set[uuid.UUID]) -> None:
        """Idempotent: members already in the class are kept as they are."""
        ...

    def enroll(self, class_id: uuid.UUID, user_id: uuid.UUID) -> None:
        """Member again (status active, no left_at), whatever the row was."""
        ...

    def leave(self, class_id: uuid.UUID, user_id: uuid.UUID, status: str, at: datetime) -> None: ...

    def remove_member(self, class_id: uuid.UUID, user_id: uuid.UUID) -> None: ...

    def remove_from_org(self, org_id: uuid.UUID, user_id: uuid.UUID) -> None:
        """Delete the user's rows in every class of the org."""
        ...

    def member_ids(self, class_id: uuid.UUID) -> list[uuid.UUID]:
        """By full name."""
        ...


class LevelRepository(Protocol):
    def get(self, org_id: uuid.UUID, level_id: uuid.UUID) -> SchoolLevel | None: ...

    def code_taken(self, org_id: uuid.UUID, code: str, exclude_id: uuid.UUID | None = None) -> bool: ...

    def overlapping(self, org_id: uuid.UUID, grade_from: int, grade_to: int, exclude_id: uuid.UUID | None = None) -> str | None:
        """Name of another level whose range meets [grade_from, grade_to]."""
        ...

    def grade_count(self, level_id: uuid.UUID) -> int: ...

    def grades_outside(self, level_id: uuid.UUID, grade_from: int, grade_to: int) -> int: ...

    def add(self, level: SchoolLevel) -> None: ...

    def remove(self, level: SchoolLevel) -> None: ...


class GradeRepository(Protocol):
    def get(self, org_id: uuid.UUID, grade_id: uuid.UUID) -> Grade | None: ...

    def by_level(self, org_id: uuid.UUID, level: int) -> Grade | None: ...

    def level_taken(self, org_id: uuid.UUID, level: int, exclude_id: uuid.UUID | None = None) -> bool: ...

    def top_level(self, org_id: uuid.UUID) -> int | None: ...

    def class_count(self, grade_id: uuid.UUID) -> int: ...

    def add(self, grade: Grade) -> None: ...

    def remove(self, grade: Grade) -> None: ...


class MemberDirectory(Protocol):
    """Accounts of the organisation (identity context)."""

    def member_ids(self, org_id: uuid.UUID, user_ids: set[uuid.UUID]) -> set[uuid.UUID]:
        """Those of `user_ids` with an active membership in the org."""
        ...

    def roles(self, org_id: uuid.UUID, user_ids: list[uuid.UUID]) -> dict[uuid.UUID, str]: ...
