# Source spec for 04-units-of-work — regenerate with:
#   python3 scripts/gen_plan.py .ai/features/2026092101-platform-foundation .ai/features/2026092101-platform-foundation/plan_spec.py

UOWS = [
    dict(
        id="UOW-01", slug="stack-and-login", title="Stack runs and users log in with org code",
        requirements=["US-01", "US-02", "US-03"], risk="high",
        demo=[
            "cp .env.example .env && docker compose up -d --build",
            "Open http://localhost:8080/api/health → status ok, db ok, storage ok",
            "Open http://localhost:8080/login, enter org `system`, `admin`, `admin12345` → forced to /change-password",
            "Set a new password → land on the super admin home",
            "Log out, log in with a wrong password → generic error; reload /login → org field prefilled",
        ],
        in_scope=["Compose stack, Dockerfiles, Caddy", "API skeleton, config, DB, errors, health",
                  "Alembic base schema (organizations, users, refresh_tokens, audit_logs), seed",
                  "Auth service + routes, lockout, refresh rotation, forced password change",
                  "Next.js scaffold, API client, login + change-password pages, role home"],
        not_in_scope=["Org CRUD (UOW-02)", "User management (UOW-03)"],
        risks=[("argon2 slow on ARM", "tune time_cost; measured in T-01-04")],
        dod=["Images build on arm64", "No token or password in logs"],
    ),
    dict(
        id="UOW-02", slug="org-management", title="Super admin manages organisations",
        requirements=["US-04"], depends_on=["UOW-01"],
        demo=[
            "Log in as super admin, open /admin/orgs",
            "Create org `TrungtamA` with admin `admin` → temporary password shown once",
            "Try to create `TRUNGTAMA` → field error",
            "Log in as trungtama/admin in a private window → forced password change → org admin home",
            "Suspend TrungtamA → that login is refused with 'Tổ chức đang bị khóa'; reactivate → allowed",
            "Soft delete a test org → hidden from list; system org shows no suspend/delete",
        ],
        in_scope=["Taxonomy + topic + tag schema and per-org seed from the Toán template",
                  "Org service and /admin/orgs API", "Admin orgs UI"],
    ),
    dict(
        id="UOW-03", slug="users-and-classes", title="Org admin imports users and manages classes",
        requirements=["US-05"], depends_on=["UOW-02"],
        demo=[
            "Log in as trungtama/admin, open /org/users, create a teacher, edit, deactivate",
            "Open /org/users/import, upload samples/students-30.csv → preview shows 30 valid rows",
            "Upload samples/students-bad.csv → rows with errors are listed, nothing created",
            "Commit the good file → download temp passwords CSV",
            "Log in as one imported student → forced password change",
            "Open /org/classes → class 10A1 lists its imported students; remove one",
            "Reset a student's password from the users page → new temp password shown once",
        ],
        in_scope=["User CRUD + reset API", "CSV/XLSX import preview/commit", "Classes API",
                  "Users, import and classes UI"],
    ),
    dict(
        id="UOW-04", slug="topics-tags-question-view", title="Topic tree, tags and full question rendering",
        requirements=["US-06", "US-07"], depends_on=["UOW-02"],
        demo=[
            "Log in as a teacher of trungtama, open /org/topics",
            "Expand Giải tích › Nguyên hàm, add 'Nguyên hàm từng phần', rename it, move it under Tích phân and back",
            "Try deleting 'Nguyên hàm' → refused; merge a test node into another → children moved",
            "Open /org/tags, create 'đổi biến' in Phương pháp, rename, try a duplicate → refused, delete",
            "Open /dev/question-preview → sample question renders KaTeX, image in option C, solution with image; toggle exam mode hides answer and solution",
        ],
        in_scope=["Topic service (create/rename/move/merge/delete) and tag API",
                  "Assets in MinIO + minimal question model + demo question seed",
                  "Topic tree UI, tags UI, QuestionView component + preview page"],
    ),
]

API = "apps/api"
WEB = "apps/web"

TICKETS = [
    # ---------------- UOW-01
    dict(id="T-01-01", uow="UOW-01", title="Compose stack, Dockerfiles, Caddy, verify script",
         layer="infra", type="chore", estimate="3h", verifies=["AC-01"],
         tests=[f"{API}/tests/test_health.py"],
         touches=["docker-compose.yml", "docker-compose.dev.yml", ".env.example", "infra/Caddyfile",
                  f"{API}/Dockerfile", f"{WEB}/Dockerfile", "scripts/verify.sh", ".gitignore", "README.md"],
         context="Everything later runs inside this compose. Caddy gives one origin (:8080 dev) so cookies are same-origin (ADR-05).",
         notes=["postgres: pgvector/pgvector:pg16 with healthcheck; minio + bucket bootstrap via minio/mc one-shot",
                "api: python:3.12-slim + uv; web: node:24-alpine, Next standalone",
                "verify.sh: routes apps/api/tests/* to pytest inside a uv env against compose postgres, apps/web/* to vitest"],
         done_when=["`docker compose up -d --build` brings all services healthy", "verify.sh runs the given tests and returns their exit code",
                    "`docker buildx build --platform linux/amd64,linux/arm64` succeeds for api and web images (or documented if buildx unavailable)"]),
    dict(id="T-01-02", uow="UOW-01", title="API skeleton, config, DB, errors, health, base migration, seed",
         layer="data", estimate="4h", depends_on=["T-01-01"], verifies=["AC-01", "AC-02"],
         tests=[f"{API}/tests/test_health.py", f"{API}/tests/test_seed.py"],
         touches=[f"{API}/pyproject.toml", f"{API}/app/main.py", f"{API}/app/core/config.py", f"{API}/app/core/db.py",
                  f"{API}/app/core/errors.py", f"{API}/app/core/storage.py", f"{API}/app/models/__init__.py",
                  f"{API}/app/models/org.py", f"{API}/app/models/user.py", f"{API}/app/models/audit.py",
                  f"{API}/migrations/env.py", f"{API}/migrations/versions/0001_base.py", f"{API}/app/seed/bootstrap.py",
                  f"{API}/tests/conftest.py"],
         assumptions=["A-04", "A-16"],
         context="Foundation of the API package. Models follow the domain model table in 03-logical-design.md.",
         notes=["Extensions citext, ltree, vector created in 0001", "Seed is idempotent (upsert by code/username)",
                "Tests use a dedicated database `examind_test`, created and migrated by conftest"],
         done_when=["/api/health reports db and storage", "Seed twice → exactly one system org and one super admin",
                    "AppError handler returns the JSON error shape"]),
    dict(id="T-01-03", uow="UOW-01", title="Auth service: argon2, JWT, login, lockout, refresh rotation, change password",
         layer="domain", estimate="3h", depends_on=["T-01-02"],
         verifies=["AC-03", "AC-04", "AC-05", "AC-06", "AC-08", "AC-09"],
         tests=[f"{API}/tests/test_auth_service.py"],
         touches=[f"{API}/app/core/security.py", f"{API}/app/services/auth.py"],
         assumptions=["A-01", "A-06", "A-07"],
         context="Pure service logic; routers come in T-01-04.",
         notes=["Identical error for unknown org/user/wrong password/inactive (timing-safe dummy hash)",
                "Refresh tokens: random 32 bytes, sha256 stored, rotated on use, reuse of a revoked token revokes all of the user's tokens"],
         done_when=["Case-insensitive org/username login works", "Lockout after 5 failures", "Suspended org refused",
                    "Refresh rotation + revoke covered by tests"]),
    dict(id="T-01-04", uow="UOW-01", title="Auth routes, cookies, deps (current_user, require_role, org scope)",
         layer="api", estimate="3h", depends_on=["T-01-03"],
         verifies=["AC-03", "AC-04", "AC-05", "AC-06", "AC-08", "AC-09"],
         tests=[f"{API}/tests/test_auth_api.py"],
         touches=[f"{API}/app/routers/auth.py", f"{API}/app/deps.py", f"{API}/app/schemas/auth.py"],
         context="HTTP surface for auth; deps reused by every later router.",
         notes=["must_change_password users get 403 password_change_required from every route except me/change-password/logout",
                "Per-IP rate limit on login (in-memory sliding window)"],
         done_when=["Cookies httpOnly SameSite=Lax", "Login p95 < 300 ms measured in test (argon2 tuned)",
                    "No password or token in logs"]),
    dict(id="T-01-05", uow="UOW-01", title="Next.js scaffold, UI primitives, API client",
         layer="web", type="chore", estimate="3h", depends_on=["T-01-01"], verifies=["AC-08"],
         tests=[f"{WEB}/src/lib/api.test.ts"],
         touches=[f"{WEB}/package.json", f"{WEB}/next.config.ts", f"{WEB}/src/app/layout.tsx", f"{WEB}/src/app/globals.css",
                  f"{WEB}/src/components/ui/", f"{WEB}/src/lib/api.ts", f"{WEB}/src/lib/types.ts", f"{WEB}/vitest.config.ts"],
         context="Shared web foundation. API client refreshes once on 401 then redirects to /login.",
         done_when=["`pnpm build` succeeds", "api client retries once after refresh (unit test)"]),
    dict(id="T-01-06", uow="UOW-01", title="Login, change-password pages, authenticated layout and role home",
         layer="web", estimate="3h", depends_on=["T-01-04", "T-01-05"], verifies=["AC-03", "AC-04", "AC-07", "AC-09"],
         tests=[f"{WEB}/src/app/(auth)/login/login.test.tsx"],
         touches=[f"{WEB}/src/app/(auth)/login/page.tsx", f"{WEB}/src/app/(auth)/change-password/page.tsx",
                  f"{WEB}/src/app/(app)/layout.tsx", f"{WEB}/src/app/(app)/page.tsx", f"{WEB}/src/lib/session.ts",
                  f"{WEB}/src/middleware.ts"],
         context="First user-visible slice. Org code remembered in localStorage (AC-07).",
         done_when=["Login form has org, username, password", "Org prefilled from last success",
                    "must_change_password redirects to /change-password", "Nav shows links by role"]),
    # ---------------- UOW-02
    dict(id="T-02-01", uow="UOW-02", title="Taxonomy, topic (ltree), tag schema and per-org seed template",
         layer="data", estimate="4h", depends_on=["T-01-02"], verifies=["AC-10"],
         tests=[f"{API}/tests/test_taxonomy_seed.py"],
         touches=[f"{API}/app/models/taxonomy.py", f"{API}/migrations/versions/0002_taxonomy.py",
                  f"{API}/app/seed/math_topics.py", f"{API}/app/seed/org_template.py"],
         assumptions=["A-10", "A-11", "A-12"],
         context="Org creation (T-02-02) seeds subjects, grades, semesters and the Toán 10–12 tree.",
         notes=["Topic labels in ltree are `t` + 12 hex chars of the id", "GiST index on path"],
         done_when=["Seeding an org creates the full tree with correct paths", "Seeding is idempotent"]),
    dict(id="T-02-02", uow="UOW-02", title="Org service and /admin/orgs API",
         layer="api", estimate="4h", depends_on=["T-02-01", "T-01-04"],
         verifies=["AC-10", "AC-11", "AC-12", "AC-13", "AC-14"],
         tests=[f"{API}/tests/test_orgs_api.py"],
         touches=[f"{API}/app/services/orgs.py", f"{API}/app/routers/admin_orgs.py", f"{API}/app/schemas/orgs.py",
                  f"{API}/app/services/audit.py"],
         assumptions=["A-01", "A-04", "A-15"],
         context="Super admin only. Suspend/delete revokes refresh tokens of the org.",
         done_when=["Create returns temp admin password once", "Invalid/duplicate code → 422/409",
                    "System org cannot be suspended/deleted", "Non super_admin → 403", "Audit rows written"]),
    dict(id="T-02-03", uow="UOW-02", title="Admin organisations UI",
         layer="web", estimate="4h", depends_on=["T-02-02", "T-01-06"], verifies=["AC-10", "AC-11", "AC-12", "AC-13"],
         tests=[f"{WEB}/src/app/(app)/admin/orgs/orgs.test.tsx"],
         touches=[f"{WEB}/src/app/(app)/admin/orgs/page.tsx", f"{WEB}/src/components/admin/OrgForm.tsx",
                  f"{WEB}/src/components/admin/OrgTable.tsx", f"{WEB}/src/components/ui/"],
         context="List with search, create dialog showing temp password once, edit, suspend/activate, delete.",
         done_when=["All org actions reachable", "Temp password copy button", "Field errors rendered"]),
    # ---------------- UOW-03
    dict(id="T-03-01", uow="UOW-03", title="User service + API: CRUD, deactivate, reset password, isolation",
         layer="api", estimate="4h", depends_on=["T-02-02"], verifies=["AC-15", "AC-18", "AC-19"],
         tests=[f"{API}/tests/test_users_api.py"],
         touches=[f"{API}/app/services/users.py", f"{API}/app/routers/users.py", f"{API}/app/schemas/users.py",
                  f"{API}/app/core/passwords.py"],
         assumptions=["A-02", "A-05", "A-09"],
         context="Teachers may manage students only (A-05).",
         done_when=["Cross-org id → 404", "Reset revokes refresh tokens", "Teacher cannot edit a teacher"]),
    dict(id="T-03-02", uow="UOW-03", title="CSV/XLSX import preview + commit, username generation",
         layer="domain", estimate="4h", depends_on=["T-03-01", "T-03-03"], verifies=["AC-16", "AC-17"],
         tests=[f"{API}/tests/test_import.py"],
         touches=[f"{API}/app/services/user_import.py", f"{API}/app/routers/users.py", "samples/students-30.csv",
                  "samples/students-bad.csv"],
         assumptions=["A-02", "A-08", "A-09"],
         context="Classes named in the file are created if missing (needs T-03-03).",
         done_when=["Diacritics stripped for usernames", "Duplicate handling", "Preview reports row errors, commit is all-or-nothing"]),
    dict(id="T-03-03", uow="UOW-03", title="Classes schema, service and API",
         layer="api", estimate="3h", depends_on=["T-02-02"], verifies=["AC-19", "AC-20"],
         tests=[f"{API}/tests/test_classes_api.py"],
         touches=[f"{API}/app/models/school_class.py", f"{API}/migrations/versions/0003_classes.py",
                  f"{API}/app/services/classes.py", f"{API}/app/routers/classes.py", f"{API}/app/schemas/classes.py"],
         context="Student may be in several classes.",
         done_when=["CRUD + members", "Isolation tests"]),
    dict(id="T-03-04", uow="UOW-03", title="Users UI: list, create, edit, deactivate, reset",
         layer="web", estimate="4h", depends_on=["T-03-01", "T-01-06"], verifies=["AC-15", "AC-18"],
         tests=[f"{WEB}/src/app/(app)/org/users/users.test.tsx"],
         touches=[f"{WEB}/src/app/(app)/org/users/page.tsx", f"{WEB}/src/components/org/UserForm.tsx"],
         context="Filter by role/class, search by name/username.",
         done_when=["Actions work for org_admin and teacher per role rules"]),
    dict(id="T-03-05", uow="UOW-03", title="Import UI with preview and temp-password download",
         layer="web", estimate="3h", depends_on=["T-03-02", "T-03-04"], verifies=["AC-16", "AC-17"],
         tests=[f"{WEB}/src/app/(app)/org/users/import/import.test.tsx"],
         touches=[f"{WEB}/src/app/(app)/org/users/import/page.tsx"],
         context="Two-step: preview then commit; download CSV of credentials once.",
         done_when=["Errors shown per row", "Credentials CSV downloads"]),
    dict(id="T-03-06", uow="UOW-03", title="Classes UI",
         layer="web", estimate="3h", depends_on=["T-03-03", "T-03-04"], verifies=["AC-20"],
         tests=[f"{WEB}/src/app/(app)/org/classes/classes.test.tsx"],
         touches=[f"{WEB}/src/app/(app)/org/classes/page.tsx", f"{WEB}/src/app/(app)/org/classes/[id]/page.tsx"],
         context="List classes, create, members add/remove.",
         done_when=["Members add/remove works"]),
    # ---------------- UOW-04
    dict(id="T-04-01", uow="UOW-04", title="Topic service (create/rename/move/merge/delete) and tags API",
         layer="api", estimate="4h", depends_on=["T-02-02"], verifies=["AC-21", "AC-22", "AC-23"],
         tests=[f"{API}/tests/test_topics_api.py", f"{API}/tests/test_tags_api.py"],
         touches=[f"{API}/app/services/topics.py", f"{API}/app/routers/topics.py", f"{API}/app/services/tags.py",
                  f"{API}/app/routers/tags.py", f"{API}/app/routers/taxonomy.py", f"{API}/app/schemas/taxonomy.py"],
         assumptions=["A-10", "A-12", "A-13"],
         context="Move rewrites the subtree path in one statement (ADR-04).",
         done_when=["Move under own descendant refused", "Delete with children refused", "Merge moves children", "Tag uniqueness per group"]),
    dict(id="T-04-02", uow="UOW-04", title="Assets in MinIO, minimal question model, demo question seed",
         layer="data", estimate="3h", depends_on=["T-02-01"], verifies=["AC-24"],
         tests=[f"{API}/tests/test_assets_api.py"],
         touches=[f"{API}/app/models/question.py", f"{API}/app/models/asset.py", f"{API}/migrations/versions/0004_questions.py",
                  f"{API}/app/routers/assets.py", f"{API}/app/routers/questions.py", f"{API}/app/seed/demo_question.py"],
         context="Question model is extended in later features; here enough for QuestionView.",
         done_when=["Upload + fetch asset with org check", "Demo question seeded for every org"]),
    dict(id="T-04-03", uow="UOW-04", title="Topic tree UI",
         layer="web", estimate="4h", depends_on=["T-04-01", "T-01-06"], verifies=["AC-21", "AC-22"],
         tests=[f"{WEB}/src/components/topics/TopicTree.test.tsx"],
         touches=[f"{WEB}/src/app/(app)/org/topics/page.tsx", f"{WEB}/src/components/topics/TopicTree.tsx"],
         context="Expandable tree, inline rename, add child, move-to dialog, merge dialog, delete.",
         done_when=["All operations reachable by keyboard and mouse"]),
    dict(id="T-04-04", uow="UOW-04", title="Tags UI",
         layer="web", estimate="2h", depends_on=["T-04-01", "T-01-06"], verifies=["AC-23"],
         tests=[f"{WEB}/src/app/(app)/org/tags/tags.test.tsx"],
         touches=[f"{WEB}/src/app/(app)/org/tags/page.tsx"],
         context="Grouped list with inline create/rename/delete.",
         done_when=["Duplicate error shown"]),
    dict(id="T-04-05", uow="UOW-04", title="QuestionView component and preview page",
         layer="web", estimate="4h", depends_on=["T-04-02", "T-01-05"], verifies=["AC-24"],
         tests=[f"{WEB}/src/components/question/QuestionView.test.tsx"],
         touches=[f"{WEB}/src/components/question/QuestionView.tsx", f"{WEB}/src/components/question/Markdown.tsx",
                  f"{WEB}/src/app/(app)/dev/question-preview/page.tsx"],
         context="The only question renderer (architecture map). react-markdown + remark-math + rehype-katex; `asset:<id>` → /api/assets/<id>.",
         done_when=["exam mode hides answer and solution", "empty parts render nothing", "images resolved in every part"]),
]
