# Source spec for 04-units-of-work — regenerate with:
#   python3 scripts/gen_plan.py .ai/features/2026092204-adaptive-review .ai/features/2026092204-adaptive-review/plan_spec.py

UOWS = [
    dict(
        id="UOW-01", slug="mastery", title="Mastery per topic follows every graded answer",
        requirements=["US-01"], risk="medium",
        demo=[
            "A student submits an exam → 'Tiến độ của tôi' shows mastery per topic, weakest first",
            "Teacher opens the class page → the student's weakest topics are listed",
            "Run `python -m app.services.mastery backfill` → mastery rebuilt identically",
        ],
        in_scope=["Mastery table + update hook + backfill", "Mastery API", "Mastery in my stats and the class overview"],
    ),
    dict(
        id="UOW-02", slug="personal-review", title="Students and teachers get personalised review exams",
        requirements=["US-02", "US-03"], depends_on=["UOW-01"], risk="high",
        demo=[
            "Student presses 'Tạo đề ôn tập' → 20 questions, plan shows 'Chuyên đề yếu: …', runs in the exam page, results immediately",
            "Mastery updates after submitting",
            "Teacher on class 10A1 → 'Giao đề ôn cá nhân' (15 câu, 30 phút) → every student's home shows their own exam",
        ],
        in_scope=["Adaptive generator", "Practice + class assignment API", "Buttons and plan display"],
    ),
    dict(
        id="UOW-03", slug="key-audit", title="Suspect answer keys are flagged for review",
        requirements=["US-04"], depends_on=["UOW-01"],
        demo=[
            "Seed: flip the key of a question answered by ≥ 10 students → run 'Kiểm tra đáp án' → it appears as 'Nghi sai đáp án' with evidence",
            "In the queue press the right option key, then Enter → approved and usable again",
            "A hard but correct question is not flagged",
        ],
        in_scope=["Detection service + worker schedule + exclusion", "Flagged group in review UI"],
    ),
]

API = "apps/api"
WEB = "apps/web"

TICKETS = [
    dict(id="T-01-01", uow="UOW-01", title="Mastery table, EMA update on grading, backfill command",
         layer="domain", estimate="3h", verifies=["AC-01", "AC-03"],
         tests=[f"{API}/tests/test_mastery.py"],
         touches=[f"{API}/migrations/versions/0010_adaptive.py", f"{API}/app/models/mastery.py", f"{API}/app/models/__init__.py",
                  f"{API}/app/services/mastery.py", f"{API}/app/services/attempts.py"],
         assumptions=["A-01"],
         context="ADR-01. Migration also adds question status 'flagged' and flag_evidence.",
         done_when=["EMA matches hand-computed values", "Backfill equals incremental"]),
    dict(id="T-01-02", uow="UOW-01", title="Mastery API (own, per student, class overview)",
         layer="api", estimate="2h", depends_on=["T-01-01"], verifies=["AC-02", "AC-08"],
         tests=[f"{API}/tests/test_mastery_api.py"],
         touches=[f"{API}/app/routers/adaptive.py", f"{API}/app/routers/__init__.py"],
         assumptions=["A-02"],
         context="Roll-up weighted by answers.",
         done_when=["Students only see their own", "Class overview lists weakest topics"]),
    dict(id="T-01-03", uow="UOW-01", title="Mastery in 'Tiến độ của tôi' and class overview UI",
         layer="web", estimate="3h", depends_on=["T-01-02"], verifies=["AC-02", "AC-08"],
         tests=[f"{WEB}/src/__tests__/mastery.test.tsx"],
         touches=[f"{WEB}/src/app/(app)/me/stats/page.tsx", f"{WEB}/src/app/(app)/org/classes/[id]/page.tsx",
                  f"{WEB}/src/components/adaptive/MasteryList.tsx", f"{WEB}/src/components/adaptive/ClassOverview.tsx", f"{WEB}/src/lib/types.ts"],
         context="Mastery bars; teacher sees per-student weakest topics.",
         done_when=["Weakest first", "Class overview table"]),
    dict(id="T-02-01", uow="UOW-02", title="Adaptive generator (weak/medium/re-ask, difficulty targeting, exclusions)",
         layer="domain", estimate="4h", depends_on=["T-01-01"], verifies=["AC-04", "AC-06"],
         tests=[f"{API}/tests/test_adaptive.py"],
         touches=[f"{API}/app/services/adaptive.py"],
         assumptions=["A-03", "A-04", "A-05"],
         context="Returns a plan with the reason for each question.",
         done_when=["Composition within ±1 of targets", "Exclusions honoured", "< 500 ms on the perf fixture"]),
    dict(id="T-02-02", uow="UOW-02", title="Practice and class adaptive-assignment API",
         layer="api", estimate="3h", depends_on=["T-02-01", "T-01-02"], verifies=["AC-05", "AC-07"],
         tests=[f"{API}/tests/test_practice_api.py"],
         touches=[f"{API}/app/routers/adaptive.py", f"{API}/app/services/adaptive.py", f"{API}/app/services/exams.py", f"{API}/app/services/attempts.py"],
         assumptions=["A-06", "A-07"],
         context="ADR-02. Practice attempts: assignment NULL, 60-minute cap, results always visible.",
         done_when=["Practice attempt starts", "One assignment per student", "Adaptive exams hidden from the exams list"]),
    dict(id="T-02-03", uow="UOW-02", title="'Tạo đề ôn tập' and 'Giao đề ôn cá nhân' UI with the plan",
         layer="web", estimate="3h", depends_on=["T-02-02", "T-01-03"], verifies=["AC-04", "AC-05", "AC-07"],
         tests=[f"{WEB}/src/__tests__/practice.test.tsx"],
         touches=[f"{WEB}/src/components/adaptive/PracticeButton.tsx", f"{WEB}/src/components/adaptive/ClassAdaptiveDialog.tsx",
                  f"{WEB}/src/app/(app)/me/stats/page.tsx", f"{WEB}/src/app/(app)/org/classes/[id]/page.tsx", f"{WEB}/src/app/(app)/home/page.tsx"],
         context="Plan summary shown before starting.",
         done_when=["Button starts practice", "Dialog assigns to class"]),
    dict(id="T-03-01", uow="UOW-03", title="Key audit: detection, evidence, worker schedule, exclusion from exams",
         layer="worker", estimate="3h", depends_on=["T-01-01"], verifies=["AC-09", "AC-11", "AC-12"],
         tests=[f"{API}/tests/test_key_audit.py"],
         touches=[f"{API}/app/services/key_audit.py", f"{API}/app/worker/main.py", f"{API}/app/routers/review.py", f"{API}/app/services/review.py"],
         assumptions=["A-08", "A-09"],
         context="ADR-03. Flagged status is outside USABLE, so bank/blueprint/adaptive exclude it automatically.",
         done_when=["Wrong key flagged", "Hard correct question not flagged", "Runs every 10 minutes"]),
    dict(id="T-03-02", uow="UOW-03", title="Flagged questions in review list and queue with evidence",
         layer="web", estimate="2h", depends_on=["T-03-01", "T-01-03"], verifies=["AC-10"],
         tests=[f"{WEB}/src/__tests__/flagged.test.tsx"],
         touches=[f"{WEB}/src/components/review/ReviewList.tsx", f"{WEB}/src/components/review/ReviewQueue.tsx", f"{WEB}/src/lib/types.ts"],
         context="Evidence: option counts and the top-quartile choice.",
         done_when=["Count badge", "Evidence panel", "Approve after fixing"]),
]
